config/routes.rb
Rails.application.routes.draw do
  get 'payment_page/index'
  get 'payment_page/success'
  devise_for :users
  #devise_for :users, :controllers => {
    #:registrations => 'users/registrations'
  #}

  resources :homepage, only: [:index]
  get "homepage/alluser"
  resources :credit_card_page, param: :public_uid
  post "credit_card_page/confirmation"
  resources :comment_page
  resources :payment_page, only: [:index]
  post "payment_page/apipost"
  get "payment_page/success"
  
  root to: "homepage#index"
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end

  def alluser
    authorize! :read, current_user
    @users = User.all
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/alluser.html.erb
<p>(secret) all user data</p>

<table>
  <tr>
    <th>username</th><th>email</th><th>password</th><th>admin</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.role %></td>
  </tr>
  <% end %>
</table>
<%= link_to "戻る", homepage_index_path %>

app/views/homepage/index.html.erb
<h1>Homepage#index</h1>
<p>Find me in app/views/homepage/index.html.erb</p>
<%= link_to "コメント一覧", comment_page_index_path %>
<%= link_to "決済ホーム", credit_card_page_index_path %>
<%= link_to "logout", destroy_user_session_path, :method => :delete %>
<%= link_to "契約解除", user_registration_path, :method => :delete %>
<%= link_to "商品を買う", payment_page_index_path %>
<% if current_user.admin? then %>
  <%= link_to "ユーザー全データ(管理者only)", homepage_alluser_path %>
<% end %>