config/routes.rb
Rails.application.routes.draw do
  get 'payment_page/index'
  get 'payment_page/success'
  devise_for :users
  #devise_for :users, :controllers => {
    #:registrations => 'users/registrations'
  #}

  resources :homepage, only: [:index]
  get "homepage/alluser"
  resources :credit_card_page, param: :public_uid
  post "credit_card_page/confirmation"
  resources :comment_page
  resources :payment_page, only: [:index]
  post "payment_page/apipost"
  get "payment_page/success"
  
  root to: "homepage#index"
end

app/controllers/credit_card_page_controller.rb
class CreditCardPageController < ApplicationController
  load_and_authorize_resource(only: [:edit, :update, :destroy], class: CreditCard)

  def index
    @user = current_user
  end

  def show
    @card = current_user.credit_card
  end

  def new
    @card = CreditCard.new
    @user = current_user
  end

  def create
    @card = CreditCard.new(card_params)
    @card.user_id = current_user.id

    if @card.save
      redirect_to credit_card_page_index_path
    end
  end

  def edit
    @user = current_user
    @card = current_user.credit_card
  end

  def update
    @card = current_user.credit_card
    @card.update(card_params)
    redirect_to credit_card_page_index_path
  end

  def destroy
    @card = CreditCard.find_by(public_uid: params[:public_uid])
    @card.destroy
    redirect_to credit_card_page_index_path
  end

  def confirmation
    @card = CreditCard.new(card_params)
    #render :new if @card.invalid?
  end

  private

  def card_params
    params.require(:credit_card).permit(:number)
  end

end

app/helpers/credit_card_page_helper.rb
module CreditCardPageHelper
end

app/views/credit_card_page/confirmation.html.erb
<%= form_for(@card, url: { controller: "credit_card_page", action: "create"}) do |f| %>
  <p>登録するクレジットカード情報</p>
  <%= @card.number %>
  <%= f.hidden_field :number %>
  <%= link_to '戻る', credit_card_page_index_path %>
  <%= f.submit 'confirm' %>
<% end %>

app/views/credit_card_page/edit.html.erb
<h1>credit card 更新</h1>
<% if @user.credit_card==nil then %>
  <p>you haven't registered your credit card yet!</p>
  <%= link_to "戻る", credit_card_page_index_path  %>
<% else %>
  <%= form_for(@card, url: {controller: "credit_card_page", action: "update"}) do |f| %>
    <%= f.number_field :number %>
    <%= f.submit "send" %>
  <% end %>
<% end %>

app/views/credit_card_page/index.html.erb
<h1>決済するところ</h1>
<%= link_to "ホームに戻る", root_path %>
<%= link_to "クレジットカード情報", credit_card_page_path(@user.public_uid) %>
<% if @user.credit_card==nil then %>
  <%= link_to "クレジットカード登録", new_credit_card_page_path %>
<% else %>
  <%= link_to "クレジットカード変更", edit_credit_card_page_path(@user.credit_card.public_uid) %>
  <%= link_to "クレジットカード登録解除", credit_card_page_path(@user.credit_card.public_uid), :method => :delete %>
<% end %>

app/views/credit_card_page/new.html.erb
<h1>credit card 登録</h1>

<% if @user.credit_card!=nil then %>
  <p>you already registered credit card</p>
  <%= link_to "戻る", credit_card_page_index_path  %>
<% else %>
  <%= form_for(@card, url: {controller: "credit_card_page", action: "confirmation"}) do |f| %>
    <%= f.number_field :number %>
    <%= f.submit "send" %>
  <% end %>
<% end %>

app/views/credit_card_page/show.html.erb
<h1>your credit card info</h1>
<% if @card==nil then %>
  <p>クレジットカードは登録されていません</p>
<% else %>
  <p>number is:</p>
  <%= @card.number %>
<% end %>
<%= link_to "戻る", credit_card_page_index_path %>