config/routes.rb
Rails.application.routes.draw do
  get 'payment_page/index'
  get 'payment_page/success'
  devise_for :users
  #devise_for :users, :controllers => {
    #:registrations => 'users/registrations'
  #}

  resources :homepage, only: [:index]
  get "homepage/alluser"
  resources :credit_card_page, param: :public_uid
  post "credit_card_page/confirmation"
  resources :comment_page
  resources :payment_page, only: [:index]
  post "payment_page/apipost"
  get "payment_page/success"
  
  root to: "homepage#index"
end

app/controllers/comment_page_controller.rb
class CommentPageController < ApplicationController
  load_and_authorize_resource(only: [:edit, :update, :destroy], class: Comment)

  def index
    @comment = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to comment_page_index_path
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to comment_page_index_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comment_page_index_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
  
end

app/helpers/comment_page_helper.rb
module CommentPageHelper
end

app/views/comment_page/edit.html.erb
<h1>コメントを更新</h1>
<%= form_for(@comment, url:{ controller: "comment_page", action: "update", id: @comment.id }) do |f|%>
  <%= f.text_field :content %>
  <%= f.submit "edit" %>
<% end %>

app/views/comment_page/index.html.erb
<h1>コメント掲載するところ</h1>
<%= link_to "ホームに戻る", root_path %>
<%= link_to "コメント新規作成する", new_comment_page_path %>

<table>
  <tr>
    <th>ユーザ</th><th>コメント</th>
  </tr>
  <% @comment.each do |comment| %>
  <tr>
    <td><%= comment.user.username %></td>
    <td><%= comment.content %></td>
    <td><a href="/comment_page/<%= comment.id %>/edit">Edit</a></td>
    <td><%= link_to "delete", comment_page_path(comment.id), :method => :delete %></td>
  </tr>
  <% end %>
</table>

app/views/comment_page/new.html.erb
<h1>コメントを投稿</h1>
<%= form_for(@comment, url: {controller: "comment_page", action: "create"}) do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "send" %>
<% end %>