config/routes.rb
Rails.application.routes.draw do
  get 'payment_page/index'
  get 'payment_page/success'
  devise_for :users
  #devise_for :users, :controllers => {
    #:registrations => 'users/registrations'
  #}

  resources :homepage, only: [:index]
  get "homepage/alluser"
  resources :credit_card_page, param: :public_uid
  post "credit_card_page/confirmation"
  resources :comment_page
  resources :payment_page, only: [:index]
  post "payment_page/apipost"
  get "payment_page/success"
  
  root to: "homepage#index"
end

app/controllers/payment_page_controller.rb
require "net/https"
require "json"

class PaymentPageController < ApplicationController
  def index
  end

  def apipost
    endpoint = URI.parse("https://urlorcx7vi.execute-api.ap-northeast-1.amazonaws.com/any/payment")
    http = Net::HTTP.new(endpoint.host, endpoint.port)
    http.use_ssl = endpoint.scheme == "https"
    headers = { "Content-Type"=>"application/json" }

    apikey = "a1b2c3d4f5"
    cardnum = current_user.credit_card.number
    params = { "apikey"=>apikey, "cardnum"=>cardnum }

    res = http.post(endpoint.path, params.to_json, headers)
    result = JSON.parse(res.body)
    result = JSON.parse(result["body"])

    if result["payment"]=="success" then
      redirect_to payment_page_success_path
    elsif result["payment"] == "wrong_key" then
      logger.info(result["body"]["payment"])
      redirect_to payment_page_index_path
    else
      logger.info(result)
      redirect_to payment_page_index_path
    end

  end

  def success
  end

end

app/helpers/payment_page_helper.rb
module PaymentPageHelper
end

app/views/payment_page/apipost.html.erb
<p>calling api ...</p>

app/views/payment_page/index.html.erb
<h1>決済方法選択画面</h1>
<h2>ECサイトで商品を選択したと過程</h2>

<p>1: API</p>
<% if current_user.credit_card.nil? then %>
  <p>you must register credit card first! to use this</p>
  <%= link_to "クレジットカードを登録する", new_credit_card_page_path %>
<% else %>
  <%= link_to "今すぐ買う!", payment_page_apipost_path, method: :post %>
<% end %>

<br/>

<p>2: 3Dセキュア</p>
<%= link_to "3Dセキュアで買う!", "https://kazumatsuhack9981.github.io/Fake3DSecureRepo/3d-secure.html"%>

app/views/payment_page/success.html.erb
<h1>無事決済完了！</h1>
<%= link_to "ホームへ戻る", homepage_index_path %>